client: client.cpp clientSocket.h clientSocket.cpp serverSocket.h serverSocket.cpp ulti.h ulti.cpp
	g++ client.cpp clientSocket.cpp ulti.cpp serverSocket.cpp -o client -std=c++17 -pthread
	mv ./client ..

rm:
	rm -f ./*.o client
	